version: '3.8'

services:
  talker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2_talker
    environment:
      - ROS_DOMAIN_ID=8
    command: /bin/bash -c "source /opt/ros/humble/setup.bash && ros2 run demo_nodes_cpp talker"
    networks:
      - ros2_network

  listener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2_listener
    environment:
      - ROS_DOMAIN_ID=8
    command: /bin/bash -c "source /opt/ros/humble/setup.bash && ros2 run demo_nodes_cpp listener"
    networks:
      - ros2_network

networks:
  ros2_network:
    driver: bridge
